docker:
        memory_size: "2048"
        image: "fonhorst/bigtop-spark-1.2"

boot2docker:
        memory_size: "6144"
        number_cpus: "4"

repo: "http://bigtop01.cloudera.org:8080/view/Releases/job/Bigtop-0.8.0/label=centos6/6/artifact/output/"
distro: centos
components: [hadoop, yarn, ambari]
namenode_ui_port: "50070"
yarn_ui_port: "8088"
hbase_ui_port: "60010"
ambari_rest_port: "8081"
